# -*- coding: utf-8 -*-
"""HackRice16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1duSkQfByTIr5nYXZnqgyMk9ET6yXu9IX
"""

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

cohort = pd.read_csv("microbiology_cultures_cohort.csv")

print("Dataset loaded successfully!")
print("Shape:", cohort.shape)

print("Columns:")
for i, col in enumerate(cohort.columns):
    print(f"{i}: {col}")

print("\nFirst 5 rows:")
display(cohort.head())

missing = pd.DataFrame({
    "missing_count": cohort.isna().sum(),
    "missing_percent": (cohort.isna().mean() * 100).round(2)
})

display(missing.sort_values("missing_count", ascending=False))

cohort["susceptibility"].value_counts()

ast = cohort.loc[
    cohort["susceptibility"].isin(["Susceptible", "Resistant"]),
    [
        "anon_id",
        "pat_enc_csn_id_coded",
        "order_proc_id_coded",
        "order_time_jittered_utc",
        "ordering_mode",
        "culture_description",
        "was_positive",
        "organism",
        "antibiotic",
        "susceptibility"
    ]
].copy()

ast["target"] = (
    ast["susceptibility"] == "Susceptible"
).astype("int8")

print("Rows:", len(ast))
print("Patients:", ast["anon_id"].nunique())
print("Cultures:", ast["order_proc_id_coded"].nunique())
print("Organisms:", ast["organism"].nunique())
print("Antibiotics:", ast["antibiotic"].nunique())

print("\nTarget distribution:")
print(ast["target"].value_counts())

antibiotics_per_culture = (
    ast.groupby("order_proc_id_coded")
    .size()
)

print(antibiotics_per_culture.describe())

print("\nDistribution:")
print(
    antibiotics_per_culture
    .value_counts()
    .sort_index()
    .head(30)
)

example_culture = ast["order_proc_id_coded"].iloc[0]

display(
    ast[
        ast["order_proc_id_coded"] == example_culture
    ][
        [
            "anon_id",
            "pat_enc_csn_id_coded",
            "order_proc_id_coded",
            "order_time_jittered_utc",
            "culture_description",
            "organism",
            "antibiotic",
            "susceptibility",
            "target"
        ]
    ].sort_values("antibiotic")
)

demographics = pd.read_csv(
    "microbiology_cultures_demographics.csv"
)

prior_organism = pd.read_csv(
    "microbiology_culture_prior_infecting_organism.csv"
)

class_exposure = pd.read_csv(
    "microbiology_cultures_antibiotic_class_exposure.csv"
)

subtype_exposure = pd.read_csv(
    "microbiology_cultures_antibiotic_subtype_exposure.csv"
)

print("Demographics:", demographics.shape)
print("Prior organism:", prior_organism.shape)
print("Class exposure:", class_exposure.shape)
print("Subtype exposure:", subtype_exposure.shape)

print("\nDEMOGRAPHICS")
print(demographics.columns.tolist())
display(demographics.head())

print("\nPRIOR ORGANISM")
print(prior_organism.columns.tolist())
display(prior_organism.head())

print("\nCLASS EXPOSURE")
print(class_exposure.columns.tolist())
display(class_exposure.head())

print("\nSUBTYPE EXPOSURE")
print(subtype_exposure.columns.tolist())
display(subtype_exposure.head())

keys = ["anon_id", "pat_enc_csn_id_coded", "order_proc_id_coded"]

ast_cultures = ast[keys].drop_duplicates()

print("AST cultures:", len(ast_cultures))

demo_matches = ast_cultures.merge(
    demographics[keys].drop_duplicates(),
    on=keys,
    how="inner"
)
print("With demographics:", len(demo_matches))

prior_matches = ast_cultures.merge(
    prior_organism[keys].drop_duplicates(),
    on=keys,
    how="inner"
)
print("With prior organism:", len(prior_matches))

class_matches = ast_cultures.merge(
    class_exposure[keys].drop_duplicates(),
    on=keys,
    how="inner"
)
print("With class exposure:", len(class_matches))

subtype_matches = ast_cultures.merge(
    subtype_exposure[keys].drop_duplicates(),
    on=keys,
    how="inner"
)
print("With subtype exposure:", len(subtype_matches))

print("\nDemographics duplicate culture keys:",
      demographics.duplicated(keys).sum())

print("Prior organism duplicate culture keys:",
      prior_organism.duplicated(keys).sum())

print("Class exposure duplicate culture keys:",
      class_exposure.duplicated(keys).sum())

print("Subtype exposure duplicate culture keys:",
      subtype_exposure.duplicated(keys).sum())

print("PRIOR ORGANISM")
print("Unique prior organisms:", prior_organism["prior_organism"].nunique())
print("Days to culture:")
display(prior_organism["prior_infecting_organism_days_to_culutre"].describe())

print("\nCLASS EXPOSURE")
print("Unique medication names:", class_exposure["medication_name"].nunique())
print("Unique antibiotic classes:", class_exposure["antibiotic_class"].nunique())
print("Time to culture:")
display(class_exposure["time_to_culturetime"].describe())

print("\nSUBTYPE EXPOSURE")
print("Unique medication names:", subtype_exposure["medication_name"].nunique())
print("Unique antibiotic subtypes:", subtype_exposure["antibiotic_subtype"].nunique())
print("Unique subtype categories:", subtype_exposure["antibiotic_subtype_category"].nunique())
print("Time to culture:")
display(subtype_exposure["medication_time_to_cultureTime"].describe())

print("\nTOP PRIOR ORGANISMS")
display(prior_organism["prior_organism"].value_counts().head(15))

print("\nTOP ANTIBIOTIC CLASSES")
display(class_exposure["antibiotic_class"].value_counts().head(15))

print("\nTOP ANTIBIOTIC SUBTYPES")
display(subtype_exposure["antibiotic_subtype"].value_counts().head(15))

print("was_positive in original cohort:")
print(cohort["was_positive"].value_counts(dropna=False))

print("\nwas_positive in AST subset:")
print(ast["was_positive"].value_counts(dropna=False))

print("\nCross-tabulation:")
print(
    pd.crosstab(
        cohort["was_positive"],
        cohort["susceptibility"],
        dropna=False
    )
)

print("\nExamples:")
print(
    cohort[
        ["was_positive", "culture_description", "organism", "antibiotic", "susceptibility"]
    ].head(20).to_string(index=False)
)

keys = ["anon_id", "pat_enc_csn_id_coded", "order_proc_id_coded"]

culture_table = ast[keys].drop_duplicates().reset_index(drop=True)
culture_table["culture_idx"] = np.arange(
    len(culture_table),
    dtype=np.int32
)

print("Unique cultures:", len(culture_table))
print("Culture table shape:", culture_table.shape)
print("Unique culture_idx:", culture_table["culture_idx"].nunique())

ast = ast.merge(
    culture_table,
    on=keys,
    how="left",
    sort=False
)

print("AST shape:", ast.shape)
print("Missing culture_idx:", ast["culture_idx"].isna().sum())
print("culture_idx dtype:", ast["culture_idx"].dtype)

demo = demographics[
    keys + ["age", "gender"]
].drop_duplicates(keys)

culture_features = culture_table.merge(
    demo,
    on=keys,
    how="left",
    sort=False
)

print("Culture feature shape:", culture_features.shape)
print("Missing age:", culture_features["age"].isna().sum())
print("Missing gender:", culture_features["gender"].isna().sum())
print("\nAge values:")
print(culture_features["age"].value_counts(dropna=False).sort_index())
print("\nGender values:")
print(culture_features["gender"].value_counts(dropna=False))

prior = prior_organism[
    keys + ["prior_organism", "prior_infecting_organism_days_to_culutre"]
].merge(
    culture_table[["culture_idx"] + keys],
    on=keys,
    how="inner",
    sort=False
)

prior["days"] = pd.to_numeric(
    prior["prior_infecting_organism_days_to_culutre"],
    errors="coerce"
).astype("float32")

print("Matched prior-organism rows:", len(prior))
print("Cultures with prior-organism history:", prior["culture_idx"].nunique())
print("Unique prior organisms:", prior["prior_organism"].nunique())
print("Missing days:", prior["days"].isna().sum())

prior_base = (
    prior.groupby("culture_idx")
    .agg(
        prior_organism_count=("prior_organism", "size"),
        days_since_prior_organism=("days", "min")
    )
    .reset_index()
)

prior_counts = (
    prior.groupby(["culture_idx", "prior_organism"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

prior_counts.columns = [
    "culture_idx"
] + [
    f"prior_{str(c)}_count"
    for c in prior_counts.columns[1:]
]

prior_features = prior_base.merge(
    prior_counts,
    on="culture_idx",
    how="left",
    sort=False
)

print("Prior feature shape:", prior_features.shape)
print("Cultures represented:", prior_features["culture_idx"].nunique())
print("Feature count:", len(prior_features.columns) - 1)
print("\nMissing values:", prior_features.isna().sum().sum())

culture_features = culture_features.merge(
    prior_features,
    on="culture_idx",
    how="left",
    sort=False
)

prior_cols = [
    c for c in prior_features.columns
    if c != "culture_idx"
]

culture_features[prior_cols] = (
    culture_features[prior_cols]
    .fillna(0)
)

print("Culture feature shape:", culture_features.shape)
print("Missing prior features:", culture_features[prior_cols].isna().sum().sum())
print("Memory usage (MB):", culture_features.memory_usage(deep=True).sum() / 1024**2)

del prior
del prior_features
del prior_counts
prior = None
prior_features = None
prior_counts = None

print("Prior-organism temporary objects cleared.")
print("Culture feature shape:", culture_features.shape)
print("Memory usage (MB):", culture_features.memory_usage(deep=True).sum() / 1024**2)

class_exp = class_exposure[
    keys + ["antibiotic_class", "time_to_culturetime"]
].merge(
    culture_table[["culture_idx"] + keys],
    on=keys,
    how="inner",
    sort=False
)

class_exp["days"] = pd.to_numeric(
    class_exp["time_to_culturetime"],
    errors="coerce"
).astype("float32")

print("Matched class-exposure rows:", len(class_exp))
print("Cultures with class exposure:", class_exp["culture_idx"].nunique())
print("Unique antibiotic classes:", class_exp["antibiotic_class"].nunique())
print("Missing days:", class_exp["days"].isna().sum())

class_base = (
    class_exp.groupby("culture_idx")
    .agg(
        class_exposure_count=("antibiotic_class", "size"),
        class_days_since_last=("days", "min")
    )
    .reset_index()
)

class_base["class_days_since_last"] = (
    class_base["class_days_since_last"].fillna(0)
)

class_parts = [class_base]

for window in [30, 90, 365]:
    w = class_exp.loc[
        class_exp["days"].notna() & (class_exp["days"] <= window),
        ["culture_idx", "antibiotic_class"]
    ]

    counts = (
        w.groupby(["culture_idx", "antibiotic_class"])
        .size()
        .unstack(fill_value=0)
        .reset_index()
    )

    counts.columns = [
        "culture_idx"
    ] + [
        f"class_{window}d_{str(c)}_count"
        for c in counts.columns[1:]
    ]

    class_parts.append(counts)

class_features = class_parts[0]

for part in class_parts[1:]:
    class_features = class_features.merge(
        part,
        on="culture_idx",
        how="left",
        sort=False
    )

class_feature_cols = [
    c for c in class_features.columns
    if c != "culture_idx"
]

class_features[class_feature_cols] = (
    class_features[class_feature_cols].fillna(0)
)

print("Class feature shape:", class_features.shape)
print("Cultures represented:", class_features["culture_idx"].nunique())
print("Feature count:", len(class_feature_cols))
print("Missing values:", class_features.isna().sum().sum())

culture_features = culture_features.merge(
    class_features,
    on="culture_idx",
    how="left",
    sort=False
)

class_cols = [
    c for c in class_features.columns
    if c != "culture_idx"
]

culture_features[class_cols] = (
    culture_features[class_cols].fillna(0)
)

print("Culture feature shape:", culture_features.shape)
print("Missing class features:", culture_features[class_cols].isna().sum().sum())
print("Memory usage (MB):", culture_features.memory_usage(deep=True).sum() / 1024**2)

del class_exp
del class_features
del class_parts
del class_base
class_exp = None
class_features = None
class_parts = None
class_base = None

print("Class-exposure temporary objects cleared.")
print("Culture feature shape:", culture_features.shape)
print("Memory usage (MB):", culture_features.memory_usage(deep=True).sum() / 1024**2)

sub_exp = subtype_exposure[
    keys + ["antibiotic_subtype", "medication_time_to_cultureTime"]
].merge(
    culture_table[["culture_idx"] + keys],
    on=keys,
    how="inner",
    sort=False
)

sub_exp["days"] = pd.to_numeric(
    sub_exp["medication_time_to_cultureTime"],
    errors="coerce"
).astype("float32")

print("Matched subtype-exposure rows:", len(sub_exp))
print("Cultures with subtype exposure:", sub_exp["culture_idx"].nunique())
print("Unique antibiotic subtypes:", sub_exp["antibiotic_subtype"].nunique())
print("Missing days:", sub_exp["days"].isna().sum())

subtype_base = (
    sub_exp.groupby("culture_idx")
    .agg(
        subtype_exposure_count=("antibiotic_subtype", "size"),
        subtype_days_since_last=("days", "min")
    )
    .reset_index()
)

subtype_parts = [subtype_base]

for window in [30, 90, 365]:
    w = sub_exp.loc[
        sub_exp["days"] <= window,
        ["culture_idx", "antibiotic_subtype"]
    ]

    counts = (
        w.groupby(["culture_idx", "antibiotic_subtype"])
        .size()
        .unstack(fill_value=0)
        .reset_index()
    )

    counts.columns = [
        "culture_idx"
    ] + [
        f"subtype_{window}d_{str(c)}_count"
        for c in counts.columns[1:]
    ]

    subtype_parts.append(counts)

subtype_features = subtype_parts[0]

for part in subtype_parts[1:]:
    subtype_features = subtype_features.merge(
        part,
        on="culture_idx",
        how="left",
        sort=False
    )

subtype_feature_cols = [
    c for c in subtype_features.columns
    if c != "culture_idx"
]

subtype_features[subtype_feature_cols] = (
    subtype_features[subtype_feature_cols].fillna(0)
)

print("Subtype feature shape:", subtype_features.shape)
print("Cultures represented:", subtype_features["culture_idx"].nunique())
print("Feature count:", len(subtype_feature_cols))
print("Missing values:", subtype_features.isna().sum().sum())

culture_features = culture_features.merge(
    subtype_features,
    on="culture_idx",
    how="left",
    sort=False
)

subtype_cols = [
    c for c in subtype_features.columns
    if c != "culture_idx"
]

culture_features[subtype_cols] = (
    culture_features[subtype_cols].fillna(0)
)

print("Culture feature shape:", culture_features.shape)
print("Missing subtype features:", culture_features[subtype_cols].isna().sum().sum())
print("Memory usage (MB):", culture_features.memory_usage(deep=True).sum() / 1024**2)

del sub_exp
del subtype_features
del subtype_parts
del subtype_base
sub_exp = None
subtype_features = None
subtype_parts = None
subtype_base = None

print("Subtype-exposure temporary objects cleared.")
print("Culture feature shape:", culture_features.shape)
print("Memory usage (MB):", culture_features.memory_usage(deep=True).sum() / 1024**2)

from sklearn.model_selection import train_test_split

patients = ast["anon_id"].unique()

train_patients, temp_patients = train_test_split(
    patients,
    test_size=0.30,
    random_state=42
)

val_patients, test_patients = train_test_split(
    temp_patients,
    test_size=0.50,
    random_state=42
)

train_mask = ast["anon_id"].isin(train_patients).to_numpy()
val_mask = ast["anon_id"].isin(val_patients).to_numpy()
test_mask = ast["anon_id"].isin(test_patients).to_numpy()

train_idx = np.flatnonzero(train_mask)
val_idx = np.flatnonzero(val_mask)
test_idx = np.flatnonzero(test_mask)

print("Patients:")
print("Train:", len(train_patients))
print("Validation:", len(val_patients))
print("Test:", len(test_patients))

print("\nRows:")
print("Train:", len(train_idx))
print("Validation:", len(val_idx))
print("Test:", len(test_idx))
print("Total:", len(train_idx) + len(val_idx) + len(test_idx))

print("\nPatient overlap:")
print("Train ∩ Val:", len(set(train_patients) & set(val_patients)))
print("Train ∩ Test:", len(set(train_patients) & set(test_patients)))
print("Val ∩ Test:", len(set(val_patients) & set(test_patients)))

categorical_cols = [
    "organism",
    "antibiotic",
    "culture_description",
    "ordering_mode",
    "age",
    "gender"
]

culture_categorical = culture_features[
    ["culture_idx", "age", "gender"]
].copy()

ast = ast.drop(columns=["age", "gender"], errors="ignore")

ast = ast.merge(
    culture_categorical,
    on="culture_idx",
    how="left",
    sort=False
)

category_maps = {}

for col in categorical_cols:
    values = ast.iloc[train_idx][col].astype(str).unique()
    category_maps[col] = {
        value: i + 1
        for i, value in enumerate(values)
    }

for col in categorical_cols:
    print(col, "training categories:", len(category_maps[col]))

print("AST rows:", len(ast))
print("Expected rows:", 1554329)

print("\nUnique order_proc IDs:", ast["order_proc_id_coded"].nunique())
print("Expected cultures:", 118737)

print("\nMissing culture_idx:", ast["culture_idx"].isna().sum())
print("Missing age:", ast["age"].isna().sum())
print("Missing gender:", ast["gender"].isna().sum())

print("\nSplit sizes:")
print("Train:", len(train_idx))
print("Validation:", len(val_idx))
print("Test:", len(test_idx))

categorical_ids = {}

for col in categorical_cols:
    values = ast[col].astype(str)
    ids = values.map(category_maps[col]).fillna(0).astype(np.int16)
    categorical_ids[col] = ids.to_numpy()

X_cat = np.column_stack([
    categorical_ids[col]
    for col in categorical_cols
])

print("Categorical matrix shape:", X_cat.shape)
print("Categorical dtype:", X_cat.dtype)

for i, col in enumerate(categorical_cols):
    print(
        col,
        "min:", X_cat[:, i].min(),
        "max:", X_cat[:, i].max(),
        "unknown:", (X_cat[:, i] == 0).sum()
    )

numeric_culture_cols = [
    c for c in culture_features.columns
    if c not in [
        "culture_idx",
        "anon_id",
        "pat_enc_csn_id_coded",
        "order_proc_id_coded",
        "age",
        "gender"
    ]
    and pd.api.types.is_numeric_dtype(culture_features[c])
]

culture_num = (
    culture_features[numeric_culture_cols]
    .fillna(0)
    .astype("float32")
    .to_numpy()
)

print("Culture numerical features:", len(numeric_culture_cols))
print("Culture numerical matrix:", culture_num.shape)
print("Dtype:", culture_num.dtype)
print(
    "Memory usage (MB):",
    culture_num.nbytes / 1024**2
)

train_culture_idx = ast.iloc[train_idx]["culture_idx"].to_numpy()

train_culture_mask = np.zeros(
    len(culture_features),
    dtype=bool
)

train_culture_mask[
    np.unique(train_culture_idx)
] = True

train_mean = culture_num[train_culture_mask].mean(axis=0)
train_std = culture_num[train_culture_mask].std(axis=0)

train_std[train_std == 0] = 1.0

culture_num = (
    (culture_num - train_mean) / train_std
).astype("float32")

print("Standardized culture matrix:", culture_num.shape)
print("Dtype:", culture_num.dtype)
print("Training mean range:", train_mean.min(), "to", train_mean.max())
print("Training std range:", train_std.min(), "to", train_std.max())
print("Constant features:", np.sum(train_std == 1.0))

y = ast["target"].to_numpy(dtype=np.float32)
culture_idx = ast["culture_idx"].to_numpy(dtype=np.int32)

print("Targets:", y.shape)
print("Culture indices:", culture_idx.shape)

print("\nTarget rates:")
print("Train:", y[train_idx].mean())
print("Validation:", y[val_idx].mean())
print("Test:", y[test_idx].mean())

print("\nCulture index range:")
print("Min:", culture_idx.min())
print("Max:", culture_idx.max())

import torch
from torch.utils.data import Dataset, DataLoader

class AntibioticResistanceDataset(Dataset):
    def __init__(self, indices):
        self.indices = indices

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, i):
        idx = self.indices[i]
        return (
            torch.tensor(X_cat[idx], dtype=torch.long),
            torch.tensor(culture_num[culture_idx[idx]], dtype=torch.float32),
            torch.tensor(y[idx], dtype=torch.float32)
        )

train_dataset = AntibioticResistanceDataset(train_idx)
val_dataset = AntibioticResistanceDataset(val_idx)
test_dataset = AntibioticResistanceDataset(test_idx)

batch_size = 512

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True,
    num_workers=0
)

val_loader = DataLoader(
    val_dataset,
    batch_size=batch_size,
    shuffle=False,
    num_workers=0
)

test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False,
    num_workers=0
)

print("Train samples:", len(train_dataset))
print("Validation samples:", len(val_dataset))
print("Test samples:", len(test_dataset))

print("\nBatches:")
print("Train:", len(train_loader))
print("Validation:", len(val_loader))
print("Test:", len(test_loader))

batch_cat, batch_num, batch_y = next(iter(train_loader))

print("\nFirst batch:")
print("Categorical:", batch_cat.shape)
print("Numerical:", batch_num.shape)
print("Target:", batch_y.shape)

import torch.nn as nn

embedding_dims = {
    "organism": 32,
    "antibiotic": 16,
    "culture_description": 4,
    "ordering_mode": 4,
    "age": 4,
    "gender": 4
}

class ResistancePredictor(nn.Module):
    def __init__(self, category_maps, num_numeric):
        super().__init__()

        self.organism_embedding = nn.Embedding(
            len(category_maps["organism"]) + 1,
            embedding_dims["organism"]
        )

        self.antibiotic_embedding = nn.Embedding(
            len(category_maps["antibiotic"]) + 1,
            embedding_dims["antibiotic"]
        )

        self.culture_embedding = nn.Embedding(
            len(category_maps["culture_description"]) + 1,
            embedding_dims["culture_description"]
        )

        self.ordering_embedding = nn.Embedding(
            len(category_maps["ordering_mode"]) + 1,
            embedding_dims["ordering_mode"]
        )

        self.age_embedding = nn.Embedding(
            len(category_maps["age"]) + 1,
            embedding_dims["age"]
        )

        self.gender_embedding = nn.Embedding(
            len(category_maps["gender"]) + 1,
            embedding_dims["gender"]
        )

        embedding_total = sum(embedding_dims.values())

        self.network = nn.Sequential(
            nn.Linear(embedding_total + num_numeric, 256),
            nn.ReLU(),
            nn.BatchNorm1d(256),
            nn.Dropout(0.30),

            nn.Linear(256, 128),
            nn.ReLU(),
            nn.BatchNorm1d(128),
            nn.Dropout(0.20),

            nn.Linear(128, 1)
        )

    def forward(self, categorical, numerical):
        organism = self.organism_embedding(categorical[:, 0])
        antibiotic = self.antibiotic_embedding(categorical[:, 1])
        culture = self.culture_embedding(categorical[:, 2])
        ordering = self.ordering_embedding(categorical[:, 3])
        age = self.age_embedding(categorical[:, 4])
        gender = self.gender_embedding(categorical[:, 5])

        x = torch.cat(
            [
                organism,
                antibiotic,
                culture,
                ordering,
                age,
                gender,
                numerical
            ],
            dim=1
        )

        return self.network(x).squeeze(1)

model = ResistancePredictor(
    category_maps=category_maps,
    num_numeric=culture_num.shape[1]
)

print(model)
print("\nParameters:", sum(p.numel() for p in model.parameters()))

model.eval()

with torch.no_grad():
    sample_logits = model(
        batch_cat,
        batch_num
    )

print("Input categorical shape:", batch_cat.shape)
print("Input numerical shape:", batch_num.shape)
print("Output shape:", sample_logits.shape)
print("First 10 logits:", sample_logits[:10])
print("First 10 probabilities:", torch.sigmoid(sample_logits[:10]))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = model.to(device)

criterion = nn.BCEWithLogitsLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001,
    weight_decay=1e-5
)

print("Device:", device)
print("Loss:", criterion)
print("Optimizer:", optimizer)

model.train()

batch_cat, batch_num, batch_y = next(iter(train_loader))

batch_cat = batch_cat.to(device)
batch_num = batch_num.to(device)
batch_y = batch_y.to(device)

optimizer.zero_grad()

logits = model(batch_cat, batch_num)
loss = criterion(logits, batch_y)

loss.backward()
optimizer.step()

print("Batch loss:", loss.item())
print("Backward pass: successful")

num_epochs = 5

for epoch in range(num_epochs):
    model.train()
    train_loss = 0.0

    for batch_cat, batch_num, batch_y in train_loader:
        batch_cat = batch_cat.to(device)
        batch_num = batch_num.to(device)
        batch_y = batch_y.to(device)

        optimizer.zero_grad()

        logits = model(batch_cat, batch_num)
        loss = criterion(logits, batch_y)

        loss.backward()
        optimizer.step()

        train_loss += loss.item() * batch_y.size(0)

    train_loss /= len(train_loader.dataset)

    model.eval()
    val_loss = 0.0

    with torch.no_grad():
        for batch_cat, batch_num, batch_y in val_loader:
            batch_cat = batch_cat.to(device)
            batch_num = batch_num.to(device)
            batch_y = batch_y.to(device)

            logits = model(batch_cat, batch_num)
            loss = criterion(logits, batch_y)

            val_loss += loss.item() * batch_y.size(0)

    val_loss /= len(val_loader.dataset)

    print(
        f"Epoch {epoch + 1}/{num_epochs} "
        f"- Train Loss: {train_loss:.4f} "
        f"- Val Loss: {val_loss:.4f}"
    )

from sklearn.metrics import roc_auc_score, average_precision_score, accuracy_score

model.eval()

val_probs = []
val_targets = []

with torch.no_grad():
    for batch_cat, batch_num, batch_y in val_loader:
        batch_cat = batch_cat.to(device)
        batch_num = batch_num.to(device)

        logits = model(batch_cat, batch_num)
        probs = torch.sigmoid(logits)

        val_probs.append(probs.cpu().numpy())
        val_targets.append(batch_y.numpy())

val_probs = np.concatenate(val_probs)
val_targets = np.concatenate(val_targets)

val_auc = roc_auc_score(val_targets, val_probs)
val_auprc = average_precision_score(val_targets, val_probs)
val_accuracy = accuracy_score(
    val_targets,
    (val_probs >= 0.5).astype(np.int8)
)

print("Validation AUROC:", val_auc)
print("Validation AUPRC:", val_auprc)
print("Validation Accuracy:", val_accuracy)

from sklearn.metrics import roc_auc_score, average_precision_score

val_results = ast.iloc[val_idx][
    ["antibiotic", "target"]
].copy()

val_results["probability"] = val_probs

rows = []

for antibiotic, group in val_results.groupby("antibiotic"):
    if group["target"].nunique() < 2:
        continue

    rows.append({
        "antibiotic": antibiotic,
        "n": len(group),
        "susceptible_rate": group["target"].mean(),
        "auroc": roc_auc_score(
            group["target"],
            group["probability"]
        ),
        "auprc": average_precision_score(
            group["target"],
            group["probability"]
        )
    })

per_antibiotic = pd.DataFrame(rows).sort_values(
    "auroc",
    ascending=False
)

print(per_antibiotic.to_string(index=False))

from sklearn.metrics import roc_auc_score, average_precision_score, accuracy_score

model.eval()

test_probs = []
test_targets = []

with torch.no_grad():
    for batch_cat, batch_num, batch_y in test_loader:
        batch_cat = batch_cat.to(device)
        batch_num = batch_num.to(device)

        logits = model(batch_cat, batch_num)
        probs = torch.sigmoid(logits)

        test_probs.append(probs.cpu().numpy())
        test_targets.append(batch_y.numpy())

test_probs = np.concatenate(test_probs)
test_targets = np.concatenate(test_targets)

test_auc = roc_auc_score(test_targets, test_probs)
test_auprc = average_precision_score(test_targets, test_probs)
test_accuracy = accuracy_score(
    test_targets,
    (test_probs >= 0.5).astype(np.int8)
)

print("Test AUROC:", test_auc)
print("Test AUPRC:", test_auprc)
print("Test Accuracy:", test_accuracy)

test_results = ast.iloc[test_idx][
    [
        "anon_id",
        "culture_idx",
        "organism",
        "antibiotic",
        "target"
    ]
].copy()

test_results["probability_susceptible"] = test_probs

print(test_results.head(10).to_string(index=False))
print("\nRows:", len(test_results))
print(
    "Probability range:",
    test_results["probability_susceptible"].min(),
    "to",
    test_results["probability_susceptible"].max()
)

ranked_test = test_results.sort_values(
    ["culture_idx", "probability_susceptible"],
    ascending=[True, False]
).copy()

ranked_test["rank"] = (
    ranked_test.groupby("culture_idx")
    .cumcount() + 1
)

print(
    ranked_test[
        [
            "culture_idx",
            "organism",
            "antibiotic",
            "probability_susceptible",
            "target",
            "rank"
        ]
    ].head(20).to_string(index=False)
)

ranking_rows = []

for culture_idx, group in ranked_test.groupby("culture_idx"):
    y_true = group["target"].to_numpy()
    y_score = group["probability_susceptible"].to_numpy()

    row = {
        "culture_idx": culture_idx,
        "susceptible_rate": y_true.mean()
    }

    for k in [1, 3, 5]:
        top = y_true[:k]

        row[f"precision_at_{k}"] = top.mean()

        if len(y_true) > 1:
            row[f"ndcg_at_{k}"] = ndcg_score(
                y_true.reshape(1, -1),
                y_score.reshape(1, -1),
                k=min(k, len(y_true))
            )
        else:
            row[f"ndcg_at_{k}"] = np.nan

    ranking_rows.append(row)

ranking_eval = pd.DataFrame(ranking_rows)

for k in [1, 3, 5]:
    precision = ranking_eval[f"precision_at_{k}"].mean()
    random_baseline = ranking_eval["susceptible_rate"].mean()
    ndcg = ranking_eval[f"ndcg_at_{k}"].mean()

    print(f"Precision@{k}: {precision:.4f}")
    print(f"Random baseline: {random_baseline:.4f}")
    print(f"NDCG@{k}: {ndcg:.4f}")
    print()

from sklearn.metrics import brier_score_loss

brier = brier_score_loss(
    test_targets,
    test_probs
)

print("Test Brier Score:", brier)

calibration = pd.DataFrame({
    "target": test_targets,
    "probability": test_probs
})

calibration["bin"] = pd.cut(
    calibration["probability"],
    bins=np.linspace(0, 1, 11),
    include_lowest=True
)

calibration_summary = (
    calibration
    .groupby("bin", observed=True)
    .agg(
        mean_predicted=("probability", "mean"),
        observed_susceptibility=("target", "mean"),
        n=("target", "size")
    )
    .reset_index()
)

print(calibration_summary.to_string(index=False))

torch.save(
    {
        "model_state_dict": model.state_dict(),
        "category_maps": category_maps,
        "numeric_culture_cols": numeric_culture_cols,
        "train_mean": train_mean,
        "train_std": train_std,
        "embedding_dims": embedding_dims
    },
    "antibiotic_resistance_model.pt"
)

print("Model saved successfully.")

from google.colab import files

files.download("antibiotic_resistance_model.pt")

